[package]
name = "krader"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["tokio", "canvas"] }
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
